####### Entity Software - Euclase Config #########
---
server:
    error:
        include-message: never
        include-binding-errors: always
        include-exception: false
        include-stacktrace: never
    tomcat:
        basedir: C:/Euclase/Log
        accesslog:
            enabled: true
    temp:
        dir: C:\Euclase\temp
    connection-timeout: 120000

logging:
    file:
        name: C:/Euclase/logs/euclase.log
    level:
        root: INFO
upload:
    base:
        dir: C:/Euclase/bulk/upload
    max:
        record: 100
jwt:
    security:
        key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
    access:
        validity: 60000
             
spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    config:
        activate:
            profile: dev
    datasource:
        initialization-mode: ALWAYS
        password: Password!23
        username: accionisservice
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver  
        url: jdbc:sqlserver://localhost;databaseName=euclase;;encrypt=true;trustServerCertificate=true
        #driverClassName: org.postgresql.Driver
        #url: jdbc:postgresql://209.159.155.84/pylon
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            #dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        open-in-view: false
        
euclase:
    document:
        prefix:
            usegeneric: true
            loan: LN
            leave: LV
            expense: EX
            service: SR
            generic: DOC
        id:
            allowuser: false
    image:
        dir: C:\Apps\EntitySC\Web\euclase\target\euclase-1.0\WEB-INF\classes\images\profile
    default:
        password: Password12#
    client:
        name: Entity Software
        address: 1 Ebun Otti Estate, Mende, Lagos, Nigeria
    reset:
        time: 1
    otp:
        expiry:
            insec: 60
    encryption:
        key:
            mian: FLWSECK-f6be2996841f1da0dfb7e27b9a3bd5bf-X
            web: onLi8HHFXqFwWBeh
    password:
        change:
            days: 30
        retry:
            count: 3
    mail:
        username: info@entitysc.com
        password: Anaconda1521@
        host: smtp.zoho.com
        port: 587
        protocol: smtp
        trust: smtp.zoho.com
admin:
    consol:
        ip: 127.0.0.1,172.20.0.78
pylon:
    test:
        url: http://pylon/api/
    profile:
        image:
            url: http://localhost:8080/pylon/images/profile/
    qrcode:
        issuer: Entity Software Euclase
        image:
            url: http://localhost:8080/pylon/images/qrcode/
    api:
        account:
            statement: http://localhost:8080/pylon/api/v1/wallet/history
        twofactor:
            enable: http://localhost:8080/pylon/api/v1/user/twofa
            validate: http://localhost:8080/pylon/api/v1/user/validate/twofa
        validate:
            pin: http://localhost:8080/pylon/api/v1/app/user/validate/pin
            securityquestion: http://localhost:8080/pylon/api/v1/app/user/validate/security-question
        otp: http://localhost:8080/pylon/api/v1/notification/otp
        qrcode:
            generate: http://localhost:8080/pylon/api/v1/qrcode
        beneficiary:
            list: http://localhost:8080/pylon/api/v1/funds-transfer/beneficiary/list
            add: http://localhost:8080/pylon/api/v1/funds-transfer/beneficiary/add
            delete: http://localhost:8080/pylon/api/v1/funds-transfer/beneficiary/delete
        dashboard: http://localhost:8080/pylon/api/v1/dashboard
        signin: http://localhost:8080/pylon/api/v1/app/user/signin
        signup: http://localhost:8080/pylon/api/v1/app/user/signup/web
        changepassword: http://localhost:8080/pylon/api/v1/app/user/change-password
        forgotpassword: http://localhost:8080/pylon/api/v1/app/user/forgot-password
        changepin: http://localhost:8080/pylon/api/v1/app/user/change-pin
        changesecurityquestion: http://localhost:8080/pylon/api/v1/app/user/change-security-question
        activation: http://localhost:8080/pylon/api/v1/app/user/signup/activation
        totp: http://localhost:8080/pylon/api/v1/authenticator/google/otp
        profile:
            details: http://localhost:8080/pylon/api/v1/dashboard
        department:
            list: http://localhost:8080/pylon/api/v1/department/list
            create: http://localhost:8080/pylon/api/v1/department
            update: http://localhost:8080/pylon/api/v1/department/update
            delete: http://localhost:8080/pylon/api/v1/department/delete
            fetch: http://localhost:8080/pylon/api/v1/department
        designation:
            list: http://localhost:8080/pylon/api/v1/designation/list
            create: http://localhost:8080/pylon/api/v1/designation
            update: http://localhost:8080/pylon/api/v1/designation/update
            delete: http://localhost:8080/pylon/api/v1/designation/delete
            fetch: http://localhost:8080/pylon/api/v1/designation
        departmentunit:
            list: http://localhost:8080/pylon/api/v1/department/unit/list
            create: http://localhost:8080/pylon/api/v1/department/unit
            update: http://localhost:8080/pylon/api/v1/department/unit/update
            delete: http://localhost:8080/pylon/api/v1/department/unit/delete
            fetch: http://localhost:8080/pylon/api/v1/department/unit
        branch:
            list: http://localhost:8080/pylon/api/v1/branch/list
            create: http://localhost:8080/pylon/api/v1/branch
            update: http://localhost:8080/pylon/api/v1/branch/update
            delete: http://localhost:8080/pylon/api/v1/branch/delete
            fetch: http://localhost:8080/pylon/api/v1/branch
        gradelevel:
            list: http://localhost:8080/pylon/api/v1/grade-level/list
            create: http://localhost:8080/pylon/api/v1/grade-level
            update: http://localhost:8080/pylon/api/v1/grade-level/update
            delete: http://localhost:8080/pylon/api/v1/grade-level/delete
            fetch: http://localhost:8080/pylon/api/v1/grade-level
        leave:
            type:
                list: http://localhost:8080/pylon/api/v1/leave/type/list
                create: http://localhost:8080/pylon/api/v1/leave/type
                update: http://localhost:8080/pylon/api/v1/leave/type/update
                delete: http://localhost:8080/pylon/api/v1/leave/type/delete
                fetch: http://localhost:8080/pylon/api/v1/leave/type
            list: http://localhost:8080/pylon/api/v1/leave/list
            create: http://localhost:8080/pylon/api/v1/leave
            update: http://localhost:8080/pylon/api/v1/leave/update
            delete: http://localhost:8080/pylon/api/v1/leave/delete
        loan:
            type:
                list: http://localhost:8080/pylon/api/v1/loan/type/list
                create: http://localhost:8080/pylon/api/v1/loan/type
                update: http://localhost:8080/pylon/api/v1/loan/type/update
                delete: http://localhost:8080/pylon/api/v1/loan/type/delete
                fetch: http://localhost:8080/pylon/api/v1/loan/type
            list: http://localhost:8080/pylon/api/v1/loan/list
            create: http://localhost:8080/pylon/api/v1/loan
            update: http://localhost:8080/pylon/api/v1/loan/update
            delete: http://localhost:8080/pylon/api/v1/loan/delete
        expense:
            type:
                list: http://localhost:8080/pylon/api/v1/expense/type/list
                create: http://localhost:8080/pylon/api/v1/expense/type
                update: http://localhost:8080/pylon/api/v1/expense/type/update
                delete: http://localhost:8080/pylon/api/v1/expense/type/delete
                fetch: http://localhost:8080/pylon/api/v1/expense/type
            list: http://localhost:8080/pylon/api/v1/expense/list
            create: http://localhost:8080/pylon/api/v1/expense
            update: http://localhost:8080/pylon/api/v1/expense/update
            delete: http://localhost:8080/pylon/api/v1/expense/delete
        service:
            request:
                list: http://localhost:8080/pylon/api/v1/service/request/list
                create: http://localhost:8080/pylon/api/v1/service/request
                update: http://localhost:8080/pylon/api/v1/service/request/update
                delete: http://localhost:8080/pylon/api/v1/service/request/delete
                fetch: http://localhost:8080/pylon/api/v1/service/request
            list: http://localhost:8080/pylon/api/v1/service/request/list
            create: http://localhost:8080/pylon/api/v1/expense
            update: http://localhost:8080/pylon/api/v1/expense/update
            delete: http://localhost:8080/pylon/api/v1/expense/delete
        document:
            template:
                fetch: http://localhost:8080/pylon/api/v1/document/template/record
                create: http://localhost:8080/pylon/api/v1/document/template
