####### Entity Software - Euclase Config #########
---
server:
    error:
        include-message: never
        include-binding-errors: always
        include-exception: false
        include-stacktrace: never
    tomcat:
        basedir: C:/Euclase/Log
        accesslog:
            enabled: true
    temp:
        dir: C:\Euclase\temp
    connection-timeout: 120000

logging:
    file:
        name: C:/Euclase/logs/euclase.log
    level:
        root: INFO
upload:
    base:
        dir: C:/Euclase/bulk/upload
    max:
        record: 100
jwt:
    security:
        key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
    access:
        validity: 60000
             
spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    config:
        activate:
            profile: dev
    datasource:
        initialization-mode: ALWAYS
        password: Anaconda1521@
        username: entityscdbuser
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver  
        url: jdbc:sqlserver://localhost;databaseName=euclase;;encrypt=true;trustServerCertificate=true
#        driverClassName: org.postgresql.Driver
#        url: jdbc:postgresql://209.159.155.84/pylon
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            #dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        open-in-view: false
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 250MB
            file-size-threshold: 5MB
        
euclase:
    temp:
        dir: C:\Apps\EntitySC\Web\euclase\target\euclase-1.0\WEB-INF\classes\temp
    document:
        allowkeyword:
            date: LEAVE, TRAINING, 
            amount: LOAN, PURCHASE, EXPENSE, INCOME, BUDGET, TRAINING, INVOICE
        archivedir: C:\Apps\EntitySC\Web\euclase\target\euclase-1.0\WEB-INF\classes\documents\archive
        prefix:
            usegeneric: false
            generic: DOC
        id:
            allowuser: false
    image:
        dir: C:\Apps\EntitySC\Web\euclase\target\euclase-1.0\WEB-INF\classes\images\profile
    default:
        password: Password12#
    client:
        name: Entity Software
        address: 1 Ebun Otti Estate, Mende, Lagos, Nigeria
    reset:
        time: 1
    otp:
        expiry:
            insec: 60
    encryption:
        key:
            mian: FLWSECK-f6be2996841f1da0dfb7e27b9a3bd5bf-X
            web: onLi8HHFXqFwWBeh
    password:
        change:
            days: 30
        retry:
            count: 3
    mail:
        username: info@entitysc.com
        password: Anaconda1521@
        host: smtp.zoho.com
        port: 587
        protocol: smtp
        trust: smtp.zoho.com
admin:
    consol:
        ip: 127.0.0.1,172.20.0.78
pylon:
    test:
        url: https://pylon/api/
    profile:
        image:
            url: http://localhost:8080/pylon/images/profile/
    qrcode:
        issuer: Entity Software Euclase
        image:
            url: http://localhost:8080/pylon/images/qrcode/
    api:
        account:
            statement: http://localhost:8080/pylon/api/v1/wallet/history
        twofactor:
            enable: http://localhost:8080/pylon/api/v1/user/twofa
            validate: http://localhost:8080/pylon/api/v1/user/validate/twofa
        validate:
            pin: http://localhost:8080/pylon/api/v1/app/user/validate/pin
            securityquestion: http://localhost:8080/pylon/api/v1/app/user/validate/security-question
        otp: http://localhost:8080/pylon/api/v1/notification/otp
        qrcode:
            generate: http://localhost:8080/pylon/api/v1/qrcode
        beneficiary:
            list: http://localhost:8080/pylon/api/v1/funds-transfer/beneficiary/list
            add: http://localhost:8080/pylon/api/v1/funds-transfer/beneficiary/add
            delete: http://localhost:8080/pylon/api/v1/funds-transfer/beneficiary/delete
        dashboard: http://localhost:8080/pylon/api/v1/dashboard
        signin: http://localhost:8080/pylon/api/v1/app/user/signin
        signup: http://localhost:8080/pylon/api/v1/app/user/signup/web
        changedefaultpassword: http://localhost:8080/pylon/api/v1/edms/password/default
        changepassword: http://localhost:8080/pylon/api/v1/app/user/change-password
        forgotpassword: http://localhost:8080/pylon/api/v1/app/user/forgot-password
        changepin: http://localhost:8080/pylon/api/v1/app/user/change-pin
        changesecurityquestion: http://localhost:8080/pylon/api/v1/app/user/change-security-question
        activation: http://localhost:8080/pylon/api/v1/app/user/signup/activation
        totp: http://localhost:8080/pylon/api/v1/authenticator/google/otp
        profile:
            details: http://localhost:8080/pylon/api/v1/dashboard
        appuser:
            generic:
               update: http://localhost:8080/pylon/api/v1/app/user/generic/update
            group:
               fetch: http://localhost:8080/pylon/api/v1/group/role/details
               update: http://localhost:8080/pylon/api/v1/group/role/update
            list: http://localhost:8080/pylon/api/v1/app/user/list
            create: http://localhost:8080/pylon/api/v1/app/user/signup/edms
            update: http://localhost:8080/pylon/api/v1/app/user/edms/update
            delete: http://localhost:8080/pylon/api/v1/app/user/delete
            fetch: http://localhost:8080/pylon/api/v1/app/user/details
            role:
              list: http://localhost:8080/pylon/api/v1/role/group/list
              fetch: http://localhost:8080/pylon/api/v1/role/group/details
              create: http://localhost:8080/pylon/api/v1/role/group/create
              update: http://localhost:8080/pylon/api/v1/role/group/update
              delete: http://localhost:8080/pylon/api/v1/role/group/delete
        department:
            list: http://localhost:8080/pylon/api/v1/department/list
            create: http://localhost:8080/pylon/api/v1/department/create
            update: http://localhost:8080/pylon/api/v1/department/update
            delete: http://localhost:8080/pylon/api/v1/department/delete
            fetch: http://localhost:8080/pylon/api/v1/department
        designation:
            list: http://localhost:8080/pylon/api/v1/designation/list
            create: http://localhost:8080/pylon/api/v1/designation/create
            update: http://localhost:8080/pylon/api/v1/designation/update
            delete: http://localhost:8080/pylon/api/v1/designation/delete
            fetch: http://localhost:8080/pylon/api/v1/designation
        departmentunit:
            department: http://localhost:8080/pylon/api/v1/department/unit
            list: http://localhost:8080/pylon/api/v1/unit/list
            create: http://localhost:8080/pylon/api/v1/unit/create
            update: http://localhost:8080/pylon/api/v1/unit/update
            delete: http://localhost:8080/pylon/api/v1/unit/delete
            fetch: http://localhost:8080/pylon/api/v1/unit
        branch:
            list: http://localhost:8080/pylon/api/v1/branch/list
            create: http://localhost:8080/pylon/api/v1/branch/create
            update: http://localhost:8080/pylon/api/v1/branch/update
            delete: http://localhost:8080/pylon/api/v1/branch/delete
            fetch: http://localhost:8080/pylon/api/v1/branch
        gradelevel:
            list: http://localhost:8080/pylon/api/v1/grade-level/list
            create: http://localhost:8080/pylon/api/v1/grade-level/create
            update: http://localhost:8080/pylon/api/v1/grade-level/update
            delete: http://localhost:8080/pylon/api/v1/grade-level/delete
            fetch: http://localhost:8080/pylon/api/v1/grade-level
        document:
            report: http://localhost:8080/pylon/api/v1/document/report
            group:
                list: http://localhost:8080/pylon/api/v1/document/group/list
                create: http://localhost:8080/pylon/api/v1/document/group/create
                update: http://localhost:8080/pylon/api/v1/document/group/update
                delete: http://localhost:8080/pylon/api/v1/document/group/delete
                fetch: http://localhost:8080/pylon/api/v1/document/group
            type:
                list: http://localhost:8080/pylon/api/v1/document/type/list
                create: http://localhost:8080/pylon/api/v1/document/type/create
                update: http://localhost:8080/pylon/api/v1/document/type/update
                delete: http://localhost:8080/pylon/api/v1/document/type/delete
                fetch: http://localhost:8080/pylon/api/v1/document/type
            create: http://localhost:8080/pylon/api/v1/document
            process: http://localhost:8080/pylon/api/v1/document/process
            search: http://localhost:8080/pylon/api/v1/document/search
            signature: http://localhost:8080/pylon/api/v1/document/signature
            archive: http://localhost:8080/pylon/api/v1/document/archive
            approve: http://localhost:8080/pylon/api/v1/document/approve
            details: http://localhost:8080/pylon/api/v1/document/details
            self: http://localhost:8080/pylon/api/v1/document/self
            pending: http://localhost:8080/pylon/api/v1/document/pending
            draft:
                fetch: http://localhost:8080/pylon/api/v1/document/draft
                delete: http://localhost:8080/pylon/api/v1/document/draft/delete
            template:
                update: http://localhost:8080/pylon/api/v1/document/template/update
            workflow:
                update: http://localhost:8080/pylon/api/v1/document/workflow/update
                history: http://localhost:8080/pylon/api/v1/document/workflow/history
        holidays:
            list: http://localhost:8080/pylon/api/v1/holidays/list
            create: http://localhost:8080/pylon/api/v1/holidays/create
            update: http://localhost:8080/pylon/api/v1/holidays/update
            delete: http://localhost:8080/pylon/api/v1/holidays/delete
            fetch: http://localhost:8080/pylon/api/v1/holidays
        sla:
            list: http://localhost:8080/pylon/api/v1/sla/list
            create: http://localhost:8080/pylon/api/v1/sla/create
            update: http://localhost:8080/pylon/api/v1/sla/update
            delete: http://localhost:8080/pylon/api/v1/sla/delete
            fetch: http://localhost:8080/pylon/api/v1/sla
        backup:
            list: http://localhost:8080/pylon/api/v1/document/backup/list
            create: http://localhost:8080/pylon/api/v1/document/backup/create
            update: http://localhost:8080/pylon/api/v1/document/backup/update
            delete: http://localhost:8080/pylon/api/v1/document/backup/delete
            fetch: http://localhost:8080/pylon/api/v1/document/backup
        restore:
            list: http://localhost:8080/pylon/api/v1/document/restore/list
            create: http://localhost:8080/pylon/api/v1/document/restore/create
        notification:
            list: http://localhost:8080/pylon/api/v1/document/notification/list
            create: http://localhost:8080/pylon/api/v1/document/notification/create
            update: http://localhost:8080/pylon/api/v1/document/notification/update
            delete: http://localhost:8080/pylon/api/v1/document/notification/delete
            fetch: http://localhost:8080/pylon/api/v1/document/notification
        pushnotification:
            list: http://localhost:8080/pylon/api/v1/notification/push/list
            create: http://localhost:8080/pylon/api/v1/notification/push/create
            update: http://localhost:8080/pylon/api/v1/notification/push/update
            delete: http://localhost:8080/pylon/api/v1/notification/push/delete
            fetch: http://localhost:8080/pylon/api/v1/notification/push
            selfupdate: http://localhost:8080/pylon/api/v1/notification/push/update/status
            selflist: http://localhost:8080/pylon/api/v1/notification/push/user

